spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  api-docs:
    enabled: true
    path: /doc/v3/api-docs
  swagger-ui:
    enabled: true
    path: /doc/index.html

jwt:
  secret: "JDu4x5vP8w2q1zR6hT9kYg3nB7cF2mE1sL4pX7iQ0oW5yV8uA9jM2dC3fN6"
  expiration.ms: 86400000 # 24小时